
name: jobtracker

include:
  - ./mongodb-docker/docker-compose.yml # Adjust path if your folder name is different (e.g., ./mongodb/docker-compose.yml)

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: dev-backend
    restart: always
    ports:
      - "5000:5000"
    working_dir: /app/server
    environment:
      - MONGO_URI=mongodb://job-mongo:27017/your-database-name
      - PORT=5000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:                                           # 👈 Add this block
    - "host.docker.internal:host-gateway"
    volumes:
      # - ./server:/app
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - job-mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: dev-client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCH_POLL=true
    depends_on:
      - backend